# fly.toml app configuration file generated for reeds on 2026-09-08T14:23:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reeds'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_ENV = 'production'
  ENABLE_SCHEDULER = 'false'
  PORT = '8080'
  SCHEDULE_DISABLED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  ports = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[[metrics]]
  port = 8080
  path = '/health'
